driver-service
SergeiKarachun/taxi-aggregator pull request #4
Opened 2024-01-12 09:35 UTC by SergeiKarachun

2024-01-17 12:36 UTC, pij1989 requested changes

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/domain/dto/ConstantUtil.java
Лучше вынести этот класс ConstantUtil из пакета dto в отдельный пакет util

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/exception/ExceptionMessageUtil.java
Лучше вынести этот класс ExceptionMessageUtil из пакета exception в отдельный пакет util

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/exception/ExceptionMessageUtil.java
> +        return "Can't create new car, please check input parameters";
Зачем возвращать константу через метод, вынести просто как константу
```suggestion
        public static final String CAN_NOT_CREATE_CAR_MESSAGE = "Can't create new car, please check input parameters";
```

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/exception/ExceptionMessageUtil.java
> +        return "Can't update new car, please check input parameters";
Зачем возвращать константу через метод, вынести просто как константу

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/exception/ExceptionMessageUtil.java
> +        return "The year of manufacture should be no more than now.";
Зачем возвращать константу через метод, вынести просто как константу

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/exception/ExceptionMessageUtil.java
> +    public static String getAlreadyExistMapMessage(HashMap<String, String> errors) {
Заменить конкретную реализацию HashMap<String, String> на интерфейс Map<String, String>

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/exception/ExceptionMessageUtil.java
> +        errors.values().forEach(str -> message.append(str));
Можно заменить лямбду на метод референс
```suggestion
        errors.values().forEach(message::append);
```

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/controller/handler/RestControllerExceptionHandler.java
> +        messages.addAll(Collections.singletonList(ex.getMessage()));
Здесь можно использовать метод add
```suggestion
        messages.add(ex.getMessage());
```

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/CarService.java
Сделать пробелы между объявлениями методов. В Intelij Idea есть горячие клавиши Ctrl+Alt+L и Ctrl+Alt+O (это сочетание для Windows, для линукса и маков может быть другое) для автоматического форматирования

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/DriverService.java
Сделать пробелы между объявлениями методов. В Intelij Idea есть горячие клавиши Ctrl+Alt+L и Ctrl+Alt+O (это сочетание для Windows, для линукса и маков может быть другое) для автоматического форматирования

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/RatingService.java
Сделать пробелы между объявлениями методов. В Intelij Idea есть горячие клавиши Ctrl+Alt+L и Ctrl+Alt+O (это сочетание для Windows, для линукса и маков может быть другое) для автоматического форматирования

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/repository/RatingRepository.java
> +                   "ORDER BY id DESC LIMIT 5) rt",
Лучше использовать текстовые блоки, появились в Java c 15 версии
@Query(value = """
                    SELECT AVG(rt.grade) 
                    FROM (SELECT grade FROM rating 
                    WHERE driver_id = :driverId 
                    ORDER BY id DESC LIMIT 5) rt
                   """,
            nativeQuery = true)

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/CarServiceImpl.java
> +        checkDate(dto.getYearOfManufacture());
объединить методы проверки в один метод, например checkCarForCreate

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/CarServiceImpl.java
> +    }
Вынести методы для маппинга в отдельный класс CarMapper в отдельный пакет mapper

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/CarServiceImpl.java
> +    }
Метод private PageRequest getPageRequest(Integer page, Integer size, String orderBy) можно вынести в отдельный утилитный класс, добавить в параметры Class clazz и использовать этот метод для разных сервисов не дублируя код
```suggestion
    private <T> PageRequest getPageRequest(Integer page, Integer size, String orderBy, Class<T> clazz) {
        if (page < 1 || size < 1) {
            throw new BadRequestException(
                    ExceptionMessageUtil.getInvalidRequestMessage(page, size));
        } else if (orderBy != null) {
            Arrays.stream(clazz.getDeclaredFields())
                    .map(Field::getName)
                    .filter(s -> s.contains(orderBy.toLowerCase()))
                    .findFirst()
                    .orElseThrow(() -> new BadRequestException(ExceptionMessageUtil.getInvalidSortingParamRequestMessage(orderBy)));
            return PageRequest.of(page - 1, size).withSort(Sort.by(Sort.Order.asc(orderBy.toLowerCase())));
        } else {
            return PageRequest.of(page - 1, size);
        }
    }
```

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/DriverServiceImpl.java
> +    private void checkIsEmailUnique(String email, HashMap<String, String> errors) {
HashMap<String, String> заменить конкретную реализацию на интерфейс Map<String, String>

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/DriverServiceImpl.java
> +    private void checkIsPhoneUnique(String phone, HashMap<String, String> errors) {
HashMap<String, String> заменить конкретную реализацию на интерфейс Map<String, String>

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/DriverServiceImpl.java
> +}
Вынести методы маппинга в отдельный класс маппер

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/DriverServiceImpl.java
> +    private PageRequest getPageRequest(Integer page, Integer size, String orderBy) {
См. замечание для CarService

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/RatingServiceImpl.java
> +        return ratingRepository.getRatingsByDriverId(driverId).orElse(5.0);
Вынести дефолтный рейтинг 5.0  в константу

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/RatingServiceImpl.java
> +    }
Вынести методы маппинга в отдельный класс маппер RatingMapper

2024-01-17 12:36 UTC, pij1989 commented on driver-service/src/main/resources/application.yaml
> +    password: postgres
лучше сенсетив данные передавать через env variable, например:  password: ${DB_PASSWORD:postgres}, если env variable DB_PASSWORD не будет передана, будет использоваться дефолтное значение postgres

2024-01-17 15:04 UTC, SergeiKarachun commented
fixed

2024-01-18 07:40 UTC, pij1989 requested changes

2024-01-18 07:40 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/CarServiceImpl.java
> +    private <T> PageRequest getPageRequest(Integer page, Integer size, String orderBy, Class<T> clazz) {
Сделай его статическим и вынеси этот метод в отдельный утилитный класс, какой-нибудь PageRequestUtil.class и ты сможешь его использовать и в CarService, и в DriverService. А сейчас у тебя дублирование кода, у тебя одинаковые методы в сервисах CarService и DriverService

2024-01-18 07:40 UTC, pij1989 commented on driver-service/src/main/java/by/sergo/driverservice/service/impl/DriverServiceImpl.java
> +    private <T> PageRequest getPageRequest(Integer page, Integer size, String orderBy, Class<T> clazz) {
См. замечание для CarService

2024-01-18 08:01 UTC, SergeiKarachun commented
fixed

2024-01-18 10:01 UTC, pij1989 approved these changes

2024-01-18 11:58 UTC, merged