passenger-service
SergeiKarachun/taxi-aggregator pull request #5
Opened 2024-01-12 09:36 UTC by SergeiKarachun

2024-01-15 09:10 UTC, AbandonedScope requested changes

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/controller/PassengerController.java
> +    }
Смотри, ты поставил аннотацию `@ResponseStatus(HttpStatus.CREATED)`, но в самом теле возвращаешь `ResponseEntity.ok(passengerResponseDto)`
Будет правильнее возвращать `ResponseEntity.created(passengerResponseDto)`

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/controller/PassengerController.java
> +    }
То же,что и в create методе, просто возвращай ResponseEntity.noContent....

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/controller/PassengerController.java
> +    }
Возвращай дто, содержащее удалённую сущность, а не просто строковый дто

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/controller/RatingController.java
> +    @GetMapping()
```suggestion
    @GetMapping
```

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/controller/RatingController.java
> +    }
Смотри, ты поставил аннотацию `@ResponseStatus(HttpStatus.CREATED)`, но в самом теле возвращаешь `ResponseEntity.ok(responseDto)`
Будет правильнее возвращать `ResponseEntity.created(responseDto)`

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/controller/handler/RestControllerExceptionHandler.java
> +    }
Ты можешь объединить эти обработчики в один

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/request/PassengerCreateUpdateRequestDto.java
Регулярные выражения выноси в константы

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/request/PassengerCreateUpdateRequestDto.java
Смотри, тут нужно реализовать локализацию, т.к. эти сообщения(`message` в аннотациях) будут отправляться пользователю
Есть два подхода:
1. Локализовать на бэке(возвращать сразу сообщения на нужном языке) - тогда нужно использовать MessegeSource и читать эти сообщения из разных файлов локалей (английской, русской, французской и тд)
2. Локализовать на фронтэнде - мы просто возвращаем ключ, например, email.not-blank, а там они сами разберутся, какое сообщение и на каком языке им показывать пользователю
Я приму любой из этих вариантов, так что выбирай сам, как будешь реализовывать

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/request/PassengerCreateUpdateRequestDto.java
Общая рекомендация по нэймингу дто:
Называй или PassengerCreateUpdateDto, или PassengerCreateUpdateRequest, но не одновременно PassengerCreateUpdateRequestDto

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/request/PassengerCreateUpdateRequestDto.java
Вообще, в качестве дто можно использовать не `class`, а `record`, тогда не придётся ставить столько аннотаций

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/response/RatingResponseDto.java
У тебя тут много лишних пустых строк

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/response/StringResponse.java
Есть лишние пустые строки

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/PassengerService.java
Общая рекомендация:
Пиши '{' и '}' даже там, где их можно опустить(в if, else и тд) - кроме лямб, там можешь не писать
Переноси на новые строки(в тех же if, else, Stream API, Optional и тд)

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/PassengerService.java
> +                ));
Тут будет правильнее не переносить параметры конструктора на новую строку

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/PassengerService.java
> +        if (field == null) {
Смотри, это условие можно поставить выше  if (field != null), чтобы просто вернуть простой ответ и всё
Тогда  if (field != null) можно будет вообще опустить и писать логику, когда  field != null не оборачивая в if, + логику по проверке field можно вынести в отдельный метод

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/PassengerService.java
> +        else return PageRequest.of(0, 10);
Вот этот код никогда не выполниться

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/PassengerService.java
> +            }
Тут посмотри в сторону использования filter, findFirst и orElseThrow

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/PassengerService.java
> +                ));
```suggestion
                .orElseThrow(() -> new NotFoundException(ExceptionMessageUtil.getNotFoundMessage("Passenger", "id", id)));
```

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/PassengerService.java
> +public class PassengerService {
Вынеси интерфейс

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/RatingService.java
> +public class RatingService {
Разнеси на интерфейс и реализацию

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/RatingService.java
> +        var passenger = passengerRepository.findById(passengerId).orElseThrow(() -> new NotFoundException(
.orElseThrow нужно писать с новой строки

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/RatingService.java
> +        ));
Тут можно просто создать метод в репозитории existsById, т.к. получать самого пользователя тебе не нужно

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/RatingService.java
> +        var passenger = passengerRepository.findById(passengerId).orElseThrow(() -> new NotFoundException(
Это можно вынести в отдельный метод

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/RatingService.java
> +        var savedRating = ratingRepository.saveAndFlush(newRating);
Почему saveAndFlush, а не просто save?

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/RatingService.java
> +        passenger.setRating(Math.floor(getAverageRating(passengerId) * 100) / 100);
Вынеси Math.floor(getAverageRating(passengerId) * 100) / 100 в отдельный метод

2024-01-15 09:10 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/exception/ExceptionMessageUtil.java
Посмотри в сторону [String.format(...)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#formatted(java.lang.Object...):~:text=by%20this%20string.-,format,-public%20static%C2%A0) или [string.formatted(...)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#formatted(java.lang.Object...):~:text=Formatter-,formatted,-public%C2%A0String), просто слаживать строки не стоит

2024-01-15 17:51 UTC, SergeiKarachun commented
updated

2024-01-15 23:59 UTC, AbandonedScope requested changes

2024-01-15 23:59 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/controller/PassengerController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(passengerServiceImpl.create(dto));
Вот как это должно быть отформатировано, поменяй, чтобы везде так было
```suggestion
        return ResponseEntity.status(HttpStatus.CREATED)
                             .body(passengerServiceImpl.create(dto));
```

2024-01-15 23:59 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/controller/PassengerController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Ты и так пишешь ResponseEntity.status(HttpStatus.NO_CONTENT), аннотацию можно не писать

2024-01-15 23:59 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/request/PassengerCreateUpdateRequest.java
> +    private final static String EMAIL_EXAMPLE = "example@gmail.com";
Лучше в отдельный класс с константами

2024-01-15 23:59 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/request/PassengerCreateUpdateRequest.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Убери эту аннотацию и пропиши просто клюевыми словами, ну или можешь не class использовать а record

2024-01-15 23:59 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/impl/PassengerServiceImpl.java
> +                    .orElseThrow(() -> new BadRequestException(ExceptionMessageUtil.getInvalidSortingParamRequestMessage(field)));
```suggestion
                    .map(Field::getName)
                    .filter(s -> s.contains(field.toLowerCase()))
                    .findFirst()
                    .orElseThrow(() -> new BadRequestException(ExceptionMessageUtil.getInvalidSortingParamRequestMessage(field)));
```

2024-01-15 23:59 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/impl/RatingServiceImpl.java
Вот, прочти и отформатируй в соответствии с [этим](https://www.quora.com/Which-coding-style-of-%E2%80%9Cif-else%E2%80%9D-is-recommended-in-Java#:~:text=In%20Java%2C%20the%20coding%20style,contains%20only%20a%20single%20statement.)

2024-01-16 15:47 UTC, SergeiKarachun commented
fixed

2024-01-18 09:05 UTC, AbandonedScope requested changes

2024-01-18 09:05 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/controller/RatingController.java
> +    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE)
Зачем тебе это `consumes = MediaType.APPLICATION_JSON_VALUE`?

2024-01-18 09:05 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/response/PassengerResponse.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
```suggestion
```

2024-01-18 09:05 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/response/RatingResponse.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
```suggestion
```

2024-01-18 09:05 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/domain/dto/response/PassengerRatingResponse.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Замени на ключевые слова

2024-01-18 09:05 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/impl/PassengerServiceImpl.java
> +                    .orElseThrow(() -> new BadRequestException(getInvalidSortingParamRequestMessage(field)));
Можешь вынести эту проверку в отдельный метод, это увеличит читаемость кода

2024-01-18 09:05 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/impl/RatingServiceImpl.java
> +    public RatingResponse createRateOfPassenger(RatingCreateRequest dto, Long passengerId) {
Можно назвать по-типу ratePassenger

2024-01-18 09:05 UTC, AbandonedScope commented on passenger-service/src/main/java/by/sergo/passengerservice/service/impl/RatingServiceImpl.java
> +    }
```suggestion
        } else {
            throw new NotFoundException(getNotFoundMessage("Passenger", "passengerId", passengerId));
        }
    }
```

2024-01-18 09:40 UTC, SergeiKarachun commented
fixed

2024-01-19 07:46 UTC, AbandonedScope approved these changes

2024-01-22 18:38 UTC, merged