ride-service
SergeiKarachun/taxi-aggregator pull request #6
Opened 2024-01-14 14:36 UTC by SergeiKarachun

2024-01-22 17:13 UTC, AbandonedScope requested changes

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/pom.xml
> +        </dependency>
По идее, эту зависимость можно поставить как runtime, разве нет?

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/controller/RideController.java
> +    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE)
Разве без APPLICATION_JSON_VALUE не работает?

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/controller/RideController.java
> +    @PutMapping(value = "/{id}/set-driver", consumes = MediaType.APPLICATION_JSON_VALUE)
Думаю, можно переименовать просто в /{id}/driver

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/controller/handler/RestControllerExceptionHandler.java
> +@RestControllerAdvice(basePackages = {"by.sergo.rideservice.controller"})
basePackages = {"by.sergo.rideservice.controller"} - вот это не является обязательным

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/service/impl/RideServiceImpl.java
> +        }
```suggestion
        if (!ride.getStatus().equals(CREATED) || ride.getDriverId() != null) {
            throw new BadRequestException(ExceptionMessageUtil.alreadyHasDriver(rideId));
        }
        
        ride.setDriverId(dto.getDriverId());
        ride.setStatus(ACCEPTED);
```

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/service/impl/RideServiceImpl.java
> +        }
Сделай здесь по примеру предложенным мной изменений в setDriverAndAcceptRide метод

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/service/impl/RideServiceImpl.java
> +        }
Сделай здесь по примеру предложенным мной изменений в setDriverAndAcceptRide метод

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/service/impl/RideServiceImpl.java
> +        }
Сделай здесь по примеру предложенным мной изменений в setDriverAndAcceptRide метод

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/service/impl/RideServiceImpl.java
> +        }
Во первых - вынеси это в отдельный метод
Во вторых - форматируй стримы
В третьих - что такое values()?

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/service/impl/RideServiceImpl.java
> +        var responsePage = rideRepository.findAllByPassengerIdAndStatus(passengerId, Status.valueOf(status.toUpperCase()), pageRequest)
Не используй var там, где из правой части выражения непонятно, что возвращается

2024-01-22 17:13 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/service/impl/RideServiceImpl.java
> +        }
```suggestion
        }
        
        return PageRequest.of(page - 1, size);
```

2024-01-22 19:51 UTC, SergeiKarachun commented on ride-service/src/main/java/by/sergo/rideservice/service/impl/RideServiceImpl.java
> +        }
Status.values() проверка status, для поиска поездок со статусом = status

2024-01-22 19:57 UTC, SergeiKarachun commented
fixed

2024-01-23 07:30 UTC, AbandonedScope approved these changes

2024-01-23 07:30 UTC, AbandonedScope commented on ride-service/src/main/java/by/sergo/rideservice/service/impl/RideServiceImpl.java
> +                    .orElseThrow(() -> new BadRequestException(ExceptionMessageUtil.getInvalidSortingParamRequestMessage(field)));
Это можно вынести в отдельный метод

2024-01-29 14:27 UTC, merged